import 'dart:async';
import 'dart:convert';
import 'package:bloc/bloc.dart';
import '../../../domain/eum/activity_level_entity.dart';
import '../../../domain/eum/gender_enum.dart';
import '../../../domain/entity/health_habits_entity.dart';
import '../../../domain/entity/meal_planning.dart';
import '../../../domain/entity/onboarding_entity.dart';
import '../../../domain/repository/onboarding_repository.dart';
import '../../../infrastructure/app_injector.dart';
import '../../../infrastructure/utils/types.dart';
import '../../service/app_data_service.dart';
import 'onboarding_state.dart';

class OnboardingCubit extends Cubit<OnboardingState> {
  final OnboardingRepository repository;

  OnboardingCubit({required this.repository})
    : super(const OnboardingLoadingState());

  /// Health Habits
  List<HealthHabits> healthHabits = [];

  /// Meal planning
  MealPlanning? mealPlan;

  /// Gender
  Gender? gender;

  /// Activity Level
  ActivityLevel? activityLevel;

  /// A stream subscriber that subscribes a stream of AI response.
  StreamSubscription<String>? promptSubscriber;

  /// Temporary string storage of AI generated meal.
  final buffer = StringBuffer();

  /// To store meal plan generated by AI in json format.
  final AppDataService appDataService = locator.get<AppDataService>();

  Future<void> saveOnboardingDetails(OnboardingEntity onboard) async {
    try {
      appDataService.onboarding = onboard;
      final OnboardingEntity onboardingEntity = await repository
          .saveOnboardingDetails(onboard);
      emit(OnboardingLoadedState(onboardingEntity));
    } catch (e) {
      emit(OnboardingErrorState(e));
    }
  }

  Future<void> generateMealPlan(OnboardingEntity onboard) async {
    try {
      emit(const OnboardingPromptState(true));
      appDataService.planStartDate = DateTime.now();
      final response = await repository.generateMeal(onboard);
      if (response != null) {
        appDataService.jsonList = JsonList.from(jsonDecode(response));
        emit(OnboardingLoadedState(onboard));
      }
      emit(const OnboardingPromptState(false));
    } catch (e) {
      emit(OnboardingErrorState(e));
    }
  }

// Future<void> sendPrompt(OnboardingEntity onboard) async {
//   try {
//     emit(const OnboardingPromptState(true));
//     promptSubscriber = repository.sendPrompt(onboard).listen(null);
//     promptSubscriber?.onData((String s) {
//       buffer.write(s);
//     });
//     promptSubscriber?.onDone(() {
//       final String fullResponse = buffer.toString();
//       // TODO: solve this chunk json decode error.
//       final jsonString = fullResponse.split('END_JSON').first.trim();
//       appDataService.json = jsonDecode(jsonString);
//       emit(OnboardingLoadedState(onboard));
//       emit(const OnboardingPromptState(false));
//     });
//   } catch (e) {
//     emit(OnboardingErrorState(e));
//   }
//   // emit(const OnboardingPromptState(true));
//   // appDataService.json = jsonDecode(repository.mockPrompt(onboard));
//   // emit(OnboardingLoadedState(onboard));
//   // emit(const OnboardingPromptState(false));
// }
}
