import 'dart:async';
import 'dart:convert';
import 'package:bloc/bloc.dart';
import '../../../domain/entity/profile_entity.dart';
import '../../../domain/entity/health_habits_entity.dart';
import '../../../domain/entity/onboarding_entity.dart';
import '../../../domain/repository/onboarding_repository.dart';
import '../../../infrastructure/app_injector.dart';
import '../../../infrastructure/utils/types.dart';
import '../../service/app_data_service.dart';
import 'onboarding_state.dart';

class OnboardingCubit extends Cubit<OnboardingState> {
  final OnboardingRepository repository;

  OnboardingCubit({required this.repository})
    : super(const OnboardingLoadingState());

  /// Health Habits
  List<HealthHabits> healthHabits = [];

  /// Meal planning
  MealPlanning? mealPlan;

  /// Gender
  Gender? gender;

  /// Activity Level
  ActivityLevel? activityLevel;

  /// A stream subscriber that subscribes a stream of AI response.
  StreamSubscription<String>? promptSubscriber;

  /// Temporary string storage of AI generated meal.
  final buffer = StringBuffer();

  /// To store meal plan generated by AI in json format.
  final AppDataService appDataService = locator.get<AppDataService>();

  /// This saves the details acquired at the time of onboarding.
  Future<void> saveOnboardingDetails(OnboardingEntity onboard) async {
    try {
      appDataService.onboarding = onboard;
      final OnboardingEntity onboardingEntity = await repository
          .saveOnboardingDetails(onboard);
      emit(OnboardingLoadedState(onboardingEntity));
    } catch (e) {
      emit(OnboardingErrorState(e));
    }
  }

  /// This generates a new plan for the first time or when old plan is expired.
  Future<void> generateMealPlan(OnboardingEntity onboard) async {
    try {
      emit(const OnboardingPromptState(true));
      appDataService.planStartDate = DateTime.now();
      final response = await repository.generateMeal(onboard);
      if (response != null) {
        // ToDo: use dart models to pass the data
        appDataService.jsonList = JsonList.from(jsonDecode(response));
        emit(OnboardingLoadedState(onboard));
      }
      emit(const OnboardingPromptState(false));
    } catch (e) {
      emit(OnboardingErrorState(e));
    }
  }
}
